# -*- coding: utf-8 -*-
"""NLP_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xytr_KIFikmZXCB4auOLEk85avID7i50
"""

import os
import json
!pip install PyMuPDF # Install PyMuPDF
import fitz  # PyMuPDF for PDF text extraction
from openai import AzureOpenAI
from google.colab import files

import os
import json
!pip install PyMuPDF # Install PyMuPDF
import fitz  # PyMuPDF for PDF text extraction
from openai import AzureOpenAI
from google.colab import files

# AZURE_OPENAI_ENDPOINT=https://openai-04.openai.azure.com/
# AZURE_OPENAI_API_KEY=<set-from-env>
# AZURE_OPENAI_API_VERSION=2024-12-01-preview
# AZURE_OPENAI_EMBEDDING_DEPLOYMENT=text-embedding-ada-002
# AZURE_OPENAI_DEPLOYMENT_NAME=gpt-4o

# 1. Setup Azure OpenAI Credentials
os.environ["AZURE_OPENAI_API_KEY"] = os.getenv("AZURE_OPENAI_API_KEY", "")
os.environ["AZURE_OPENAI_API_VERSION"] = "2024-12-01-preview"
os.environ["AZURE_OPENAI_ENDPOINT"] = os.getenv("AZURE_OPENAI_ENDPOINT", "")
AZURE_OPENAI_DEPLOYMENT_NAME = "gpt-4o"

# Initialize the Azure OpenAI Client
# client = AzureOpenAI(
#     api_key=os.environ["AZURE_OPENAI_API_KEY"],
#     api_version=os.environ["AZURE_OPENAI_API_VERSION"],
#     azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"]
# )

# Initialize Client
try:
    client = AzureOpenAI(
        api_key=os.environ["AZURE_OPENAI_API_KEY"],
        api_version=os.environ["AZURE_OPENAI_API_VERSION"],
        azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"]
    )
except ValueError as e:
    print(f"Configuration Error: {e}")
    print("Did you forget to add the 'https://' to your AZURE_OPENAI_ENDPOINT?")

# Step 3: Define the JSON Schema (We only ask for the questions array per chunk to save tokens)
schema = {
  "type": "object",
  "properties": {
    "questions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "question_no": {"type": "integer"},
          "section": {"type": "string"},
          "mcq_option": {"type": ["string", "null"]},
          "sub_questions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "sub_question_no": {"type": "string"},
                "answer": {"type": "string"}
              },
              "required": ["sub_question_no", "answer"]
            }
          },
          "whole_answer": {"type": "string"},
          "total_marks": {"type": "integer"}
        },
        "required":["question_no", "section", "whole_answer", "total_marks"]
      }
    }
  },
  "required": ["questions"]
}

# Step 4: Upload PDF
print("Please upload your Marking Scheme PDF:")
uploaded = files.upload()
pdf_filename = list(uploaded.keys())[0]

# Step 5: Extract Text Page by Page and Chunk it
def get_pdf_chunks(file_path, pages_per_chunk=2):
    pages_text =[]
    with fitz.open(file_path) as doc:
        # Skip first 2 pages if they are just general instructions (optional, but saves tokens)
        for page in doc:
            pages_text.append(page.get_text("text"))

    chunks =[]
    # Process 2 pages at a time to stay safely under the output token limit
    for i in range(0, len(pages_text), pages_per_chunk):
        chunk_text = "\n".join(pages_text[i:i + pages_per_chunk])
        chunks.append(chunk_text)
    return chunks

chunks = get_pdf_chunks(pdf_filename)
print(f"\nDivided the PDF into {len(chunks)} chunks to prevent token limits.")

# Step 6: Process Each Chunk with Azure OpenAI
all_extracted_questions =[]

system_prompt = f"""
You are an expert data extraction assistant.
Extract question and answer data from the provided text snippet of a CBSE Biology marking scheme.

You MUST return the output ONLY as a valid JSON object strictly adhering to this schema:
{json.dumps(schema)}

Rules:
1. `question_no` MUST be an integer.
2. `section`: Identify the section (A, B, C, D, E). If not visible, infer from the question type.
3. `mcq_option`: For MCQs, extract ONLY the correct option letter (e.g., "A", "B"). Output `null` if none applies.
4. `sub_questions`: If a question has parts (a, b, OR choices), put the part letter in `sub_question_no` and text in `answer`.
5. `whole_answer`: The complete answer text.
6. `total_marks`: Find the final aggregated marks on the right side and store as integer.
If a chunk contains partial questions, extract whatever is visible.
"""

for i, chunk_text in enumerate(chunks):
    if len(chunk_text.strip()) < 50:
        continue # Skip completely empty pages

    print(f"Processing chunk {i+1} of {len(chunks)}...")

    try:
        response = client.chat.completions.create(
            model=AZURE_OPENAI_DEPLOYMENT_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Extract the questions from this chunk:\n\n{chunk_text}"}
            ],
            response_format={ "type": "json_object" },
            temperature=0.0,
            max_tokens=4000 # Force maximum output allowance
        )

        chunk_json = json.loads(response.choices[0].message.content)
        all_extracted_questions.extend(chunk_json.get("questions",[]))

    except Exception as e:
        print(f"Error processing chunk {i+1}: {e}")

# Step 7: Merge any questions that got split across pages
merged_questions = {}
for q in all_extracted_questions:
    q_no = q.get("question_no")

    if q_no in merged_questions:
        # If the question was split across a page boundary, combine the text
        merged_questions[q_no]["whole_answer"] += "\n" + q.get("whole_answer", "")
        if "sub_questions" in q and q["sub_questions"]:
            if "sub_questions" not in merged_questions[q_no]:
                merged_questions[q_no]["sub_questions"] = []
            merged_questions[q_no]["sub_questions"].extend(q["sub_questions"])
    else:
        merged_questions[q_no] = q

# Convert merged dictionary back to a sorted list
final_questions_list = [merged_questions[key] for key in sorted(merged_questions.keys())]

final_json = {
    "paper_code": "57/6/2",
    "subject": "BIOLOGY (Subject Code–044)",
    "questions": final_questions_list
}

# Step 8: Save and Download
output_filename = "full_populated_marking_scheme.json"
with open(output_filename, "w", encoding="utf-8") as json_file:
    json.dump(final_json, json_file, indent=4, ensure_ascii=False)

print(f"\n✅ Success! Extracted a total of {len(final_questions_list)} questions. Downloading {output_filename}...")
files.download(output_filename)



"""# student answer sheet text extraction"""

!sudo apt-get update
!sudo apt-get install tesseract-ocr
!pip install pytesseract PyMuPDF Pillow opencv-python-headless numpy

!pip install pymupdf pillow openai
!pip install paddlepaddle -q
!pip install paddleocr -q

"""#ocr"""

import pytesseract
from PIL import Image

# If using Windows, specify path to tesseract executable
def ocr(img):
  pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

  # Load image
  image = Image.open("sample.png")

  # Extract text
  text = pytesseract.image_to_string(image)

  print("Extracted Text:")
  print(text)

!pip install PyMuPDF # Install PyMuPDF
import json
import base64
import fitz
import re
from io import BytesIO
from PIL import Image
from google.colab import files
from openai import AzureOpenAI


# -----------------------------
# Azure OpenAI Setup
# -----------------------------

AZURE_KEY      = os.getenv("AZURE_OPENAI_API_KEY", "")
AZURE_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT", "")
MODEL          = "gpt-4o"

client = AzureOpenAI(
    api_key=AZURE_KEY,
    api_version="2024-12-01-preview",
    azure_endpoint=AZURE_ENDPOINT
)


# -----------------------------
# Upload PDF
# -----------------------------

print("📄 Upload student handwritten answer sheet PDF")
uploaded = files.upload()
pdf_file = list(uploaded.keys())[0]


# -----------------------------
# PDF → base64 images (high DPI)
# -----------------------------

def pdf_to_base64_images(pdf_path, dpi=250):
    doc    = fitz.open(pdf_path)
    images = []
    for page in doc:
        pix = page.get_pixmap(dpi=dpi)
        img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
        buf = BytesIO()
        img.save(buf, format="PNG")
        images.append(base64.b64encode(buf.getvalue()).decode())
    print(f"  ✅ Converted {len(images)} pages at {dpi} DPI")
    return images

base64_images = pdf_to_base64_images(pdf_file)


# -----------------------------
# System Prompt
# -----------------------------

SYSTEM_PROMPT = """
You are an expert at reading handwritten exam answer sheets and extracting structured data.

Your job is to carefully read each page and extract every question's answer into JSON.

OUTPUT FORMAT — return ONLY a valid JSON object, no markdown, no explanation:

{
  "questions": [
    {
      "question_no": <integer>,
      "section": "<A/B/C/D or empty string>",
      "mcq_option": "<A/B/C/D or null if not MCQ>",
      "sub_questions": [
        {
          "sub_question_no": "<a/b/c/i/ii/iii>",
          "whole_answer": "<full handwritten answer text>"
        }
      ],
      "whole_answer": "<full answer if no sub-questions, else empty string>",
      "total_marks": null
    }
  ]
}

STRICT RULES:
1. Detect ALL question numbers written on the sheet (e.g. Q1, Q.1, 1., 1)
2. Detect sub-questions (a, b, c OR i, ii, iii) and keep them SEPARATE in sub_questions array
3. If a question has sub-parts → put each sub-part answer in sub_questions, leave whole_answer as ""
4. If a question has NO sub-parts → put the full answer in whole_answer, leave sub_questions as []
5. For MCQ questions → set mcq_option to the selected option letter (A/B/C/D), whole_answer = ""
6. Transcribe handwriting faithfully — do NOT correct or paraphrase answers
7. If a question is attempted but left blank → whole_answer = ""
8. If you cannot read a word → write [illegible]
9. total_marks is always null (do not fill it)
10. Do NOT skip any question you can see on the page
"""


# -----------------------------
# Process pages in batches of 2
# (avoids token limit issues)
# -----------------------------

def extract_from_pages(page_images, page_range_label):
    """Send a batch of pages to GPT and return parsed questions list."""

    image_content = [
        {
            "type": "image_url",
            "image_url": {"url": f"data:image/png;base64,{img}", "detail": "high"}
        }
        for img in page_images
    ]

    image_content.append({
        "type": "text",
        "text": f"These are pages {page_range_label} of the answer sheet. Extract ALL questions and answers visible on these pages."
    })

    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": image_content}
            ],
            response_format={"type": "json_object"},
            temperature=0,
            max_tokens=4096
        )

        raw  = response.choices[0].message.content.strip()
        data = json.loads(raw)
        return data.get("questions", [])

    except Exception as e:
        print(f"  ⚠️  Error on pages {page_range_label}: {e}")
        return []


# -----------------------------
# Batch processing
# -----------------------------

BATCH_SIZE = 2   # pages per API call — increase to 3 if your pages are sparse

all_questions = []

for i in range(0, len(base64_images), BATCH_SIZE):
    batch       = base64_images[i : i + BATCH_SIZE]
    page_label  = f"{i+1}–{min(i+BATCH_SIZE, len(base64_images))}"
    print(f"  🔍 Processing pages {page_label}...")
    questions   = extract_from_pages(batch, page_label)
    print(f"     → Extracted {len(questions)} question(s)")
    all_questions.extend(questions)


# -----------------------------
# Merge duplicate question numbers
# (same question split across page batches)
# -----------------------------

def merge_questions(questions):
    """
    If the same question_no appears more than once (split across page batches),
    merge their sub_questions and whole_answer.
    """
    merged = {}

    for q in questions:
        q_no = q.get("question_no")

        if q_no not in merged:
            merged[q_no] = q
        else:
            existing = merged[q_no]

            # Merge sub_questions — avoid duplicates by sub_question_no
            existing_subs = {s["sub_question_no"]: s for s in existing.get("sub_questions", [])}
            for sub in q.get("sub_questions", []):
                sub_no = sub["sub_question_no"]
                if sub_no not in existing_subs:
                    existing_subs[sub_no] = sub
                else:
                    # Append text if same sub appears again (page overlap)
                    if sub["whole_answer"] not in existing_subs[sub_no]["whole_answer"]:
                        existing_subs[sub_no]["whole_answer"] += " " + sub["whole_answer"]

            existing["sub_questions"] = list(existing_subs.values())

            # Merge whole_answer
            new_whole = q.get("whole_answer", "").strip()
            if new_whole and new_whole not in existing.get("whole_answer", ""):
                existing["whole_answer"] = (existing.get("whole_answer", "") + " " + new_whole).strip()

    # Sort by question number
    return [merged[k] for k in sorted(merged.keys())]


merged_questions = merge_questions(all_questions)

print(f"\n✅ Total unique questions extracted: {len(merged_questions)}")


# -----------------------------
# Validate & clean output
# -----------------------------

def clean_question(q):
    return {
        "question_no":  int(q.get("question_no", 0)),
        "section":      str(q.get("section", "")),
        "mcq_option":   q.get("mcq_option"),           # keep None or string
        "sub_questions": [
            {
                "sub_question_no": str(s.get("sub_question_no", "")),
                "whole_answer":    str(s.get("whole_answer", "")).strip()
            }
            for s in q.get("sub_questions", [])
        ],
        "whole_answer": str(q.get("whole_answer", "")).strip(),
        "total_marks":  None
    }

final_output = {
    "questions": [clean_question(q) for q in merged_questions]
}


# -----------------------------
# Preview first 3 questions
# -----------------------------

print("\n📋 Preview (first 3 questions):")
for q in final_output["questions"][:3]:
    print(json.dumps(q, indent=2))


# -----------------------------
# Save & Download
# -----------------------------

output_file = "student_answers.json"
with open(output_file, "w", encoding="utf-8") as f:
    json.dump(final_output, f, indent=4, ensure_ascii=False)

files.download(output_file)
print(f"\n✅ Extraction complete → {output_file}")



"""# embeddig using BERT and storing in Chroma DB"""

pip install chromadb transformers torch

import json
import torch
import chromadb
from transformers import BertTokenizer, BertModel

client = chromadb.Client()
collection = client.get_or_create_collection(name="marking_scheme_vectors_5")

with open("full_populated_marking_scheme.json", "r") as f:
    data = json.load(f)

questions = data["questions"]

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")
model.eval()

def get_embedding(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512)
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state[:, 0, :].squeeze().tolist()


def get_scheme_answer(q):
    """
    Build the full answer text for a question.
    Priority: whole_answer → concatenate sub_questions[].answer
    Marking scheme uses 'answer' key inside sub_questions (NOT 'whole_answer')
    """
    whole = q.get("whole_answer", "").strip()
    if whole:
        return whole

    parts = []
    for sub in q.get("sub_questions", []):
        sub_ans = sub.get("answer", "").strip()          # ✅ scheme uses 'answer' key
        sub_no  = sub.get("sub_question_no", "")
        if sub_ans:
            parts.append(f"({sub_no}) {sub_ans}")

    return " | ".join(parts) if parts else ""


documents  = []
embeddings = []
metadatas  = []
ids        = []
point_id   = 0

for q in questions:
    q_no        = q.get("question_no")
    section     = q.get("section", "")
    mcq_option  = q.get("mcq_option")
    total_marks = q.get("total_marks")   # ✅ keep None as-is, don't default to 1 here

    answer = get_scheme_answer(q)

    if not answer:
        print(f"⚠️  Q{q_no} has no answer text, skipping.")
        continue

    # ✅ Embed with question context for better retrieval
    text = f"Question {q_no}: {answer}"
    emb  = get_embedding(text)

    documents.append(answer)
    embeddings.append(emb)

    metadatas.append({
        "question_no": q_no,
        "section":     section if section else "",
        "mcq_option":  mcq_option if mcq_option else "",   # ✅ ChromaDB needs string not None
        # ✅ total_marks: store actual value; if None fall back to 0 so evaluator can detect missing
        "total_marks": total_marks if total_marks is not None else 0
    })

    ids.append(str(point_id))
    point_id += 1

    print(f"  ✅ Q{q_no} | section={section} | marks={total_marks} | mcq={mcq_option} | answer={answer[:60]}...")


# ✅ Verify no duplicate question_nos were stored
stored_q_nos = [m["question_no"] for m in metadatas]
duplicates   = [q for q in stored_q_nos if stored_q_nos.count(q) > 1]

if duplicates:
    print(f"\n⚠️  Duplicate question_nos detected: {set(duplicates)}")
    print("   Retrieval by question_no may return wrong chunk — deduplicate your JSON!")
else:
    print(f"\n✅ No duplicates found.")

collection.add(
    documents=documents,
    embeddings=embeddings,
    metadatas=metadatas,
    ids=ids
)

print(f"\n✅ Stored {point_id} questions in ChromaDB!")
print(f"   Questions stored: {sorted(stored_q_nos)}")

import math

pip install chromadb openai





import os
import json
import math
import chromadb
from openai import AzureOpenAI

# ---------------------------------------------------
# Azure OpenAI Setup
# ---------------------------------------------------

os.environ["AZURE_OPENAI_API_KEY"] = os.getenv("AZURE_OPENAI_API_KEY", "")
os.environ["AZURE_OPENAI_API_VERSION"] = "2024-12-01-preview"
os.environ["AZURE_OPENAI_ENDPOINT"] = os.getenv("AZURE_OPENAI_ENDPOINT", "")

MODEL = "gpt-4o"

client_llm = AzureOpenAI(
    api_key=os.environ["AZURE_OPENAI_API_KEY"],
    api_version=os.environ["AZURE_OPENAI_API_VERSION"],
    azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"]
)

# ---------------------------------------------------
# ChromaDB Setup
# ---------------------------------------------------

client = chromadb.Client()
collection = client.get_collection(name="marking_scheme_vectors_5")

# ---------------------------------------------------
# Load Student Answers
# ---------------------------------------------------

with open("student_answers.json") as f:
    student_json = json.load(f)

results = []
total_obtained = 0.0
total_marks_sum = 0.0
skipped = []

# ---------------------------------------------------
# Helper: Build student's effective answer
# Priority: whole_answer → sub_questions[].whole_answer
# ---------------------------------------------------

def get_student_answer(q):

    whole = q.get("whole_answer", "").strip()

    if whole:
        return whole, "whole_answer"

    parts = []

    for sub in q.get("sub_questions", []):
        sub_ans = sub.get("whole_answer", "").strip()
        sub_no = sub.get("sub_question_no") or sub.get("question_no", "")

        if sub_ans:
            parts.append(f"({sub_no}) {sub_ans}")

    combined = " | ".join(parts)

    return combined, "sub_questions" if combined else "empty"


# ---------------------------------------------------
# Helper: LLM Descriptive Evaluation
# ---------------------------------------------------

def evaluate_descriptive(correct_answer, student_answer, max_marks):

    prompt = f"""
You are evaluating a student's exam answer.

Correct Answer:
{correct_answer}

Student Answer:
{student_answer}

Maximum Marks: {max_marks}

Tasks:
1. Compute semantic similarity between the two answers (0.0 to 1.0).
2. Assign marks out of {max_marks} proportional to conceptual correctness.

Rules:
- Accept synonyms, paraphrasing, and equivalent scientific terms
- Ignore spelling and grammar mistakes
- Award partial marks for partially correct answers
- Similarity must reflect conceptual overlap, not just word matching
- If student answer covers all key points → marks close to {max_marks}
- If student answer is partially correct → proportional marks
- If student answer is completely wrong or irrelevant → marks = 0

Return ONLY this JSON (no markdown, no explanation):
{{
  "similarity": <float 0.0 to 1.0>,
  "marks": <float 0.0 to {max_marks}>
}}
"""

    response = client_llm.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": "You are a strict but fair exam evaluator. Return only valid JSON."},
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

    reply = response.choices[0].message.content.strip()

    # Remove markdown if present
    if reply.startswith("```"):
        reply = reply.split("```")[1]
        if reply.startswith("json"):
            reply = reply[4:]
        reply = reply.strip()

    try:

        data = json.loads(reply)

        similarity = max(0.0, min(1.0, float(data["similarity"])))

        raw_marks = max(0.0, min(float(max_marks), float(data["marks"])))

        # Apply ceiling but ensure it does not exceed max marks
        obtained = min(max_marks, math.ceil(raw_marks))

    except Exception as e:

        print(f"⚠️ LLM parse error: {e} | Raw reply: {reply}")
        similarity = 0.0
        obtained = 0.0

    return similarity, obtained


# ---------------------------------------------------
# Main Evaluation Loop
# ---------------------------------------------------

for q in student_json["questions"]:

    q_no = q["question_no"]
    student_mcq_option = q.get("mcq_option")

    print("\n" + "="*55)
    print(f"📝 Evaluating Question {q_no}...")

    # Retrieve marking scheme
    retrieved = collection.get(where={"question_no": q_no})

    if not retrieved["documents"]:
        print(f"⚠️ No marking scheme found for Q{q_no}, skipping.")
        skipped.append(q_no)
        continue

    scheme_answer = retrieved["documents"][0]
    scheme_metadata = retrieved["metadatas"][0]

    correct_mcq_option = scheme_metadata.get("mcq_option", "")
    max_marks = float(scheme_metadata.get("total_marks", 0))

    if max_marks == 0:
        print(f"⚠️ Q{q_no} has total_marks=0 or null in marking scheme, skipping.")
        skipped.append(q_no)
        continue

    print(f"Question worth : {max_marks} marks")

    # ---------------------------------------------------
    # Determine Question Type
    # ---------------------------------------------------

    is_mcq = bool(student_mcq_option) and bool(correct_mcq_option)

    if is_mcq:

        if student_mcq_option == correct_mcq_option:

            similarity = 1.0
            obtained = max_marks

            print(f"[MCQ] ✅ Correct ({student_mcq_option}) | {obtained}/{max_marks}")

        else:

            similarity = 0.0
            obtained = 0.0

            print(f"[MCQ] ❌ Wrong (student: {student_mcq_option}, correct: {correct_mcq_option}) | 0/{max_marks}")

    else:

        student_answer, source = get_student_answer(q)

        print(f"Answer source : {source}")
        print(f"SCHEME  [{len(scheme_answer)}c] : {scheme_answer[:100]}{'...' if len(scheme_answer)>100 else ''}")
        print(f"STUDENT [{len(student_answer)}c] : {student_answer[:100] if student_answer else '⚠️ EMPTY'}")

        if not student_answer:

            similarity = 0.0
            obtained = 0.0

            print(f"[Descriptive] No answer provided → 0/{max_marks}")

        else:

            similarity, obtained = evaluate_descriptive(
                scheme_answer,
                student_answer,
                max_marks
            )

        print(f"[Descriptive] Similarity: {similarity:.2f} | Marks: {obtained}/{max_marks}")

    # ---------------------------------------------------
    # Store Result
    # ---------------------------------------------------

    results.append({
        "question_no": q_no,
        "type": "MCQ" if is_mcq else "Descriptive",
        "similarity": round(similarity, 4),
        "marks_obtained": obtained,
        "max_marks": max_marks
    })

    total_obtained += obtained
    total_marks_sum += max_marks


# ---------------------------------------------------
# Final Output
# ---------------------------------------------------

output = {
    "results": results,
    "total_obtained": round(total_obtained, 2),
    "out_of": total_marks_sum,
    "percentage": round((total_obtained / total_marks_sum * 100), 2) if total_marks_sum > 0 else 0,
    "skipped": skipped
}

with open("evaluation_result.json", "w") as f:
    json.dump(output, f, indent=4)

print("\n" + "="*55)
print("✅ Evaluation Complete!")
print(f"Score      : {total_obtained} / {total_marks_sum}")
print(f"Percentage : {output['percentage']}%")

if skipped:
    print(f"Skipped    : Q{skipped} (no scheme or total_marks=0)")

print("="*55)

"""# Combine BERTScore + NLI (Strongest approach)"""

import os
import json
import math
import chromadb
from openai import AzureOpenAI

# ---------------------------------------------------
# Azure OpenAI Setup
# ---------------------------------------------------

os.environ["AZURE_OPENAI_API_KEY"] = os.getenv("AZURE_OPENAI_API_KEY", "")
os.environ["AZURE_OPENAI_API_VERSION"] = "2024-12-01-preview"
os.environ["AZURE_OPENAI_ENDPOINT"] = os.getenv("AZURE_OPENAI_ENDPOINT", "")

MODEL = "gpt-4o"

client_llm = AzureOpenAI(
    api_key=os.environ["AZURE_OPENAI_API_KEY"],
    api_version=os.environ["AZURE_OPENAI_API_VERSION"],
    azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"]
)

# ---------------------------------------------------
# ChromaDB Setup
# ---------------------------------------------------

client = chromadb.Client()
collection = client.get_collection(name="marking_scheme_vectors_5")

# ---------------------------------------------------
# Load Student Answers
# ---------------------------------------------------

with open("student_answers.json") as f:
    student_json = json.load(f)

results = []
total_obtained = 0.0
total_marks_sum = 0.0
skipped = []

# ---------------------------------------------------
# Helper: Build student's effective answer
# Priority: whole_answer → sub_questions[].whole_answer
# ---------------------------------------------------

def get_student_answer(q):

    whole = q.get("whole_answer", "").strip()

    if whole:
        return whole, "whole_answer"

    parts = []

    for sub in q.get("sub_questions", []):
        sub_ans = sub.get("whole_answer", "").strip()
        sub_no = sub.get("sub_question_no") or sub.get("question_no", "")

        if sub_ans:
            parts.append(f"({sub_no}) {sub_ans}")

    combined = " | ".join(parts)

    return combined, "sub_questions" if combined else "empty"


# ---------------------------------------------------
# Helper: LLM Descriptive Evaluation
# ---------------------------------------------------

def evaluate_descriptive(correct_answer, student_answer, max_marks):

    prompt = f"""
You are evaluating a student's exam answer.

Correct Answer:
{correct_answer}

Student Answer:
{student_answer}

Maximum Marks: {max_marks}

Tasks:
1. Compute semantic similarity between the two answers (0.0 to 1.0).
2. Assign marks out of {max_marks} proportional to conceptual correctness.

Rules:
- Accept synonyms, paraphrasing, and equivalent scientific terms
- Ignore spelling and grammar mistakes
- Award partial marks for partially correct answers
- Similarity must reflect conceptual overlap, not just word matching
- If student answer covers all key points → marks close to {max_marks}
- If student answer is partially correct → proportional marks
- If student answer is completely wrong or irrelevant → marks = 0

Return ONLY this JSON (no markdown, no explanation):
{{
  "similarity": <float 0.0 to 1.0>,
  "marks": <float 0.0 to {max_marks}>
}}
"""

    response = client_llm.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": "You are a strict but fair exam evaluator. Return only valid JSON."},
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

    reply = response.choices[0].message.content.strip()

    # Remove markdown if present
    if reply.startswith("```"):
        reply = reply.split("```")[1]
        if reply.startswith("json"):
            reply = reply[4:]
        reply = reply.strip()

    try:

        data = json.loads(reply)

        similarity = max(0.0, min(1.0, float(data["similarity"])))

        raw_marks = max(0.0, min(float(max_marks), float(data["marks"])))

        # Apply ceiling but ensure it does not exceed max marks
        obtained = min(max_marks, math.ceil(raw_marks))

    except Exception as e:

        print(f"⚠️ LLM parse error: {e} | Raw reply: {reply}")
        similarity = 0.0
        obtained = 0.0

    return similarity, obtained


# ---------------------------------------------------
# Main Evaluation Loop
# ---------------------------------------------------

for q in student_json["questions"]:

    q_no = q["question_no"]
    student_mcq_option = q.get("mcq_option")

    print("\n" + "="*55)
    print(f"📝 Evaluating Question {q_no}...")

    # Retrieve marking scheme
    retrieved = collection.get(where={"question_no": q_no})

    if not retrieved["documents"]:
        print(f"⚠️ No marking scheme found for Q{q_no}, skipping.")
        skipped.append(q_no)
        continue

    scheme_answer = retrieved["documents"][0]
    scheme_metadata = retrieved["metadatas"][0]

    correct_mcq_option = scheme_metadata.get("mcq_option", "")
    max_marks = float(scheme_metadata.get("total_marks", 0))

    if max_marks == 0:
        print(f"⚠️ Q{q_no} has total_marks=0 or null in marking scheme, skipping.")
        skipped.append(q_no)
        continue

    print(f"Question worth : {max_marks} marks")

    # ---------------------------------------------------
    # Determine Question Type
    # ---------------------------------------------------

    is_mcq = bool(student_mcq_option) and bool(correct_mcq_option)

    if is_mcq:

        if student_mcq_option == correct_mcq_option:

            similarity = 1.0
            obtained = max_marks

            print(f"[MCQ] ✅ Correct ({student_mcq_option}) | {obtained}/{max_marks}")

        else:

            similarity = 0.0
            obtained = 0.0

            print(f"[MCQ] ❌ Wrong (student: {student_mcq_option}, correct: {correct_mcq_option}) | 0/{max_marks}")

    else:

        student_answer, source = get_student_answer(q)

        print(f"Answer source : {source}")
        print(f"SCHEME  [{len(scheme_answer)}c] : {scheme_answer[:100]}{'...' if len(scheme_answer)>100 else ''}")
        print(f"STUDENT [{len(student_answer)}c] : {student_answer[:100] if student_answer else '⚠️ EMPTY'}")

        if not student_answer:

            similarity = 0.0
            obtained = 0.0

            print(f"[Descriptive] No answer provided → 0/{max_marks}")

        else:

            similarity, obtained = evaluate_descriptive_opensource_1(scheme_answer,
                student_answer,
                max_marks
                )

        print(f"[Descriptive] Similarity: {similarity:.2f} | Marks: {obtained}/{max_marks}")

    # ---------------------------------------------------
    # Store Result
    # ---------------------------------------------------

    results.append({
        "question_no": q_no,
        "type": "MCQ" if is_mcq else "Descriptive",
        "similarity": round(similarity, 4),
        "marks_obtained": obtained,
        "max_marks": max_marks
    })

    total_obtained += obtained
    total_marks_sum += max_marks


# ---------------------------------------------------
# Final Output
# ---------------------------------------------------

output = {
    "results": results,
    "total_obtained": round(total_obtained, 2),
    "out_of": total_marks_sum,
    "percentage": round((total_obtained / total_marks_sum * 100), 2) if total_marks_sum > 0 else 0,
    "skipped": skipped
}

with open("evaluation_result.json", "w") as f:
    json.dump(output, f, indent=4)

print("\n" + "="*55)
print("✅ Evaluation Complete!")
print(f"Score      : {total_obtained} / {total_marks_sum}")
print(f"Percentage : {output['percentage']}%")

if skipped:
    print(f"Skipped    : Q{skipped} (no scheme or total_marks=0)")

print("="*55)

!pip install bert-score
from bert_score import score as bert_score
from transformers import pipeline

nli = pipeline("text-classification", model="cross-encoder/nli-deberta-v3-small")

def evaluate_descriptive_opensource_1(correct_answer, student_answer, max_marks):

    # ── Component 1: BERTScore (keyword/concept coverage) ──
    _, _, F1 = bert_score(
        [student_answer],
        [correct_answer],
        lang="en",
        model_type="bert-base-uncased",
        verbose=False
    )
    bertscore_f1 = float(F1[0])

    # ── Component 2: NLI (logical entailment) ──────────────
    nli_result = nli(f"{student_answer} [SEP] {correct_answer}")[0]
    label      = nli_result["label"]
    score      = nli_result["score"]

    if label == "ENTAILMENT":
        nli_score = score
    elif label == "NEUTRAL":
        nli_score = score * 0.5
    else:
        nli_score = 0.0

    # ── Weighted combination ────────────────────────────────
    # BERTScore: did student cover the concepts?
    # NLI:       did student answer logically match the scheme?
    similarity = (0.5 * bertscore_f1) + (0.5 * nli_score)
    obtained   = round(similarity * max_marks, 2)

    print(f"    BERTScore F1 : {bertscore_f1:.3f}")
    print(f"    NLI score    : {nli_score:.3f}  ({label})")
    print(f"    Combined     : {similarity:.3f}")

    return float(similarity), obtained

"""#ROUGE + BERTScore (Classic NLP + Neural)"""

!pip install rouge_score
from rouge_score import rouge_scorer
from bert_score import score as bert_score

rouge = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

def evaluate_descriptive_opensource(correct_answer, student_answer, max_marks):

    # ── ROUGE: n-gram overlap (classic NLP) ────────────────
    rouge_scores = rouge.score(correct_answer, student_answer)
    rouge_avg    = (
        rouge_scores["rouge1"].fmeasure +
        rouge_scores["rouge2"].fmeasure +
        rouge_scores["rougeL"].fmeasure
    ) / 3

    # ── BERTScore: semantic overlap (neural NLP) ───────────
    _, _, F1 = bert_score(
        [student_answer], [correct_answer],
        lang="en", model_type="bert-base-uncased", verbose=False
    )
    bert_f1 = float(F1[0])

    # ── Combine ─────────────────────────────────────────────
    similarity = (0.4 * rouge_avg) + (0.6 * bert_f1)
    obtained   = round(similarity * max_marks, 2)

    print(f"    ROUGE avg    : {rouge_avg:.3f}")
    print(f"    BERTScore F1 : {bert_f1:.3f}")
    print(f"    Combined     : {similarity:.3f}")

    return float(similarity), obtained

import os
import json
import math
import chromadb

with open("/content/student_answers (1).json") as f:
    student_json = json.load(f)

client = chromadb.Client()
collection = client.get_collection(name="marking_scheme_vectors_4")

def get_student_answer(q):

    whole = q.get("whole_answer", "").strip()

    if whole:
        return whole, "whole_answer"

    parts = []

    for sub in q.get("sub_questions", []):
        sub_ans = sub.get("whole_answer", "").strip()
        sub_no = sub.get("sub_question_no") or sub.get("question_no", "")

        if sub_ans:
            parts.append(f"({sub_no}) {sub_ans}")

    combined = " | ".join(parts)

    return combined, "sub_questions" if combined else "empty"

results = []
total_obtained = 0.0
total_marks_sum = 0.0
skipped = []

for q in student_json["questions"]:

    q_no = q["question_no"]
    student_mcq_option = q.get("mcq_option")

    print("\n" + "="*55)
    print(f"📝 Evaluating Question {q_no}...")

    # Retrieve marking scheme
    retrieved = collection.get(where={"question_no": q_no})

    if not retrieved["documents"]:
        print(f"⚠️ No marking scheme found for Q{q_no}, skipping.")
        skipped.append(q_no)
        continue

    scheme_answer = retrieved["documents"][0]
    scheme_metadata = retrieved["metadatas"][0]

    correct_mcq_option = scheme_metadata.get("mcq_option", "")
    max_marks = float(scheme_metadata.get("total_marks", 0))

    if max_marks == 0:
        print(f"⚠️ Q{q_no} has total_marks=0 or null in marking scheme, skipping.")
        skipped.append(q_no)
        continue

    print(f"Question worth : {max_marks} marks")

    # ---------------------------------------------------
    # Determine Question Type
    # ---------------------------------------------------

    is_mcq = bool(student_mcq_option) and bool(correct_mcq_option)

    if is_mcq:

        if student_mcq_option == correct_mcq_option:

            similarity = 1.0
            obtained = max_marks

            print(f"[MCQ] ✅ Correct ({student_mcq_option}) | {obtained}/{max_marks}")

        else:

            similarity = 0.0
            obtained = 0.0

            print(f"[MCQ] ❌ Wrong (student: {student_mcq_option}, correct: {correct_mcq_option}) | 0/{max_marks}")

    else:

        student_answer, source = get_student_answer(q)

        print(f"Answer source : {source}")
        print(f"SCHEME  [{len(scheme_answer)}c] : {scheme_answer[:100]}{'...' if len(scheme_answer)>100 else ''}")
        print(f"STUDENT [{len(student_answer)}c] : {student_answer[:100] if student_answer else '⚠️ EMPTY'}")

        if not student_answer:

            similarity = 0.0
            obtained = 0.0

            print(f"[Descriptive] No answer provided → 0/{max_marks}")

        else:

            similarity, obtained =evaluate_descriptive_opensource(
                scheme_answer,
                student_answer,
                max_marks
            )

        print(f"[Descriptive] Similarity: {similarity:.2f} | Marks: {obtained}/{max_marks}")

    # ---------------------------------------------------
    # Store Result
    # ---------------------------------------------------

    results.append({
        "question_no": q_no,
        "type": "MCQ" if is_mcq else "Descriptive",
        "similarity": round(similarity, 4),
        "marks_obtained": obtained,
        "max_marks": max_marks
    })

    total_obtained += obtained
    total_marks_sum += max_marks


# ---------------------------------------------------
# Final Output
# ---------------------------------------------------

output = {
    "results": results,
    "total_obtained": round(total_obtained, 2),
    "out_of": total_marks_sum,
    "percentage": round((total_obtained / total_marks_sum * 100), 2) if total_marks_sum > 0 else 0,
    "skipped": skipped
}

with open("evaluation_result.json", "w") as f:
    json.dump(output, f, indent=4)

print("\n" + "="*55)
print("✅ Evaluation Complete!")
print(f"Score      : {total_obtained} / {total_marks_sum}")
print(f"Percentage : {output['percentage']}%")

if skipped:
    print(f"Skipped    : Q{skipped} (no scheme or total_marks=0)")

print("="*55)



"""#"We extract noun phrase concepts and subject-verb-object relationship triples from both answers using SpaCy dependency parsing, then semantically match concepts using sentence transformers, and verify overall conceptual alignment using zero-shot classification — this evaluates core meaning rather than surface text similarity."
"""

